name: Build and Test MacOS
on:
  [push, pull_request]

jobs:
  build__and_test:
    name: Build And Test IDTF-to-U3D converter
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Test U3D converter
      shell: bash
      run: |
        cd build
        ./IDTFConverter -en 1 -rzf 0 -pq 500 -input ../Samples/idtf/bimba.idtf -output ../Samples/idtf/bimba.u3d
    - name: Test IDTFLib converter
      shell: bash
      run: |
        mkdir Samples/out_test
        cd build/libIDTFTest
        ./libIDTFTest
    - name: Upload Test U3D converter result
      uses: actions/upload-artifact@v3
      with:
        name: bimba
        path: Samples/idtf/bimba.u3d
    - name: Upload Test IDTFLib converter result
      uses: actions/upload-artifact@v3
      with:
        name: bimba
        path: Samples/out_test/bimba.u3d
