name: Linux

on:
  [push, pull_request]

jobs:
  linux_build:
    name: Build Nexus (Linux)
    runs-on: ubuntu-20.04 #in order to deploy, need to use oldest supported version

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        version: '5.15.2'
    - name: Install dependencies
      run: |
       sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libglew-dev
       cd ..
       git clone --single-branch --branch devel https://github.com/cnr-isti-vclab/vcglib
    - name: Configure and Build
      shell: bash
      run: |
        mkdir build
        cd build
        cmake ..
        make -j4
