name: MacOS

on:
  [push, pull_request]

jobs:
  macos_build:
    name: Build Nexus (MacOS)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        version: '5.15.2'
    - name: Install dependencies
      run: |
       cd ..
       git clone --single-branch --branch devel https://github.com/cnr-isti-vclab/vcglib
    - name: Configure and Build
      shell: bash
      run: |
        mkdir build
        mkdir install
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=../install ..
        make -j4
        make install
    - name: Deploy
      shell: bash
      run: |
        cd install
        macdeployqt nxsview.app -executable=nxsview.app/Contents/MacOS/nxsbuild -executable=nxsview.app/Contents/MacOS/nxscompress -executable=nxsview.app/Contents/MacOS/nxsedit
        rm -r bin
        rm -r lib
        tar -cvzf nxsview-macos.tar.gz *
    - name: Upload nxsview Portable
      uses: actions/upload-artifact@v3
      with:
        name: nxsview_macos_portable
        path: install/nxsview-macos.tar.gz
