name: DownloadExternalLibraries

on:
  #[push, pull_request] #just for test release scripts
  workflow_dispatch: #manual run
    inputs:
      version:
        description: 'MeshLab Version'
        required: true
        default: 'YYYY.MM'

jobs:
  DownloadExternalLibraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download MeshLab repo
        uses: actions/checkout@v2
        with:
          repository: cnr-isti-vclab/meshlab
          ref: MeshLab-${{ github.event.inputs.version }}
          submodules: recursive
          path: meshlab
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
          version: '5.15.2'
      - name: Configure MeshLab
        run: |
          sudo apt-get install -y mesa-common-dev libglu1-mesa-dev
          sudo apt-get install -y cmake ninja-build libgmp-dev libmpfr-dev libtbb-dev
          cd meshlab
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Copy External Libraries
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git -rm -rf downloads
          mkdir -p downloads
          cp -r meshlab/src/external/downloads/* ./downloads
      - name: Commit External Libraries
        run: |
          git add downloads/*
          git commit -m "External Libraries ${{ github.event.inputs.version }}" -a 
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}


